# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    
    - CONDA_PY=27
    - CONDA_PY=35
    - CONDA_PY=36
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "oT3Z8EZLGXXlV7A+YFVaMONR5Ec97/ef7KtHgkNVWQPlGaQ/UndEHzcqrIn8FX2lsB6OH7DLvt59+dP3TRRQJSReo2H+7CnA6zwUUBJm31oux2bULTNX/h3tHNy2IEMH6NKgVM5suhMtQs4agWdPnRf7e6y/QC+tUSD/4WsKA4sf4MNb3+Z0sE4I+WCXtTuD0XHkk4/Ndh4KCQRrPHSGjQz3vvBu5EwelxZP83gzL6fiy5oTmUYgERhiMn6nSox3N+sfAE+M5OxhUAZRmTiZ/8tYRBTJoGOudknBh0uHygXKs4Y/T63kKeTXZd+xnM774S9DuZ1SnphdJIAGqaXwCd4VY9tm/11UU9MrRgHL0Zn+hxLsulCRTIRP4wfQeEXwl0LXdBp/8I0LwKkjQOhTIJw3NCyqd1BhM9slIaEYjQ6zDf6h0a7Sq5I1oTljE7YR/z1VzbSnkM04xWwzd3HoIpzp7UDeH4LNbtaeFE8L/Xu1kL7+nD/7UoBK3Pj6lcWUBU1+Wz0t0niHtNhQgUr2FwZK+S0ez5ca6pElfcti+fl36ecormC0YTdRNXIhesOx9DJ+DmmHMxWjsnjpKKNGtWlmbEe4qZ2eoViTUoTmmre/fug1gmpfetcjYQHDc1xUjb7xNXXESOjX82RB6BlRELT1q+m0eHHybg3MzWypGWs="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
