travis:
  secure:
    BINSTAR_TOKEN: HEtFo/VfJkps+oXqHfvTbLmRQZBxrLnI0JC0V5CaxRfT7FYJqVsedKdHTI151DDI198I8QW8vaTc18ZbiXheqWK0ESpJfUUCsbDw0Ju4d4QagzxacqW4ukxssMlDFR5FhGTEbkrtpJpXaYfpZ5R5hOuHq5kmoEShah226r5Tpc/daNiMe0McoskqSxWSMVi3FnqVCF3RLSCNYJyXGDr9bOR5LnvACHUJBXxfJYw/DddNM0bTrdHxpM4KrfZ099NDQPxM767HRi2esH7zf1iDDp26IrTKxTDjc+ud0zTNsEpObq8Jq4pjJ5OwUvJcctgPXIHHaq5dlHnFHgqB/yZbk6L8CJv5Eyg824U5BUxtWxwjxL+YEoclRKRTMPEw7aarndAxcEhuzq/hAe49veMY0Uf4KqL6yDv/gmiMo0BQInRHyXUA2Hiz8536ufFUKogWY0J2G/3CCCmeunLHe9ev6xs0XdiVvc2CPFCaYA9zqx4ReAxL0Dw+CYgcFrfbLRZ0o3cSJhSwHktk/SK5IREpHMgGznydMmxJQbJnShDNhf8aaK4BF6LNhhGXMV9Iz6hRIaa8kDppYeXg1ZwRK6KBr1niYfZopYO/7NnVGwjGvFhGlz8FrGYRoHmgeJW14i7jYAE5PAiyKsyF2cKk1/reSJ+SE2GspoirtgEA678Eu0Y=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
