travis:
  secure:
    BINSTAR_TOKEN: V/y3IoROsYT70PhZe3aLBRvF6yIstGbamCxNMJsMZMUsa+wg0NSE+OlSLO2Z9MZOdfLayh5ozEVW/JuLlrkzZlinoTMbNCT6xVzzPg92pjlTXPa3fRDzROWxCvBFMdl/k+c24m3H75HIJG6/OHI6g6j5B7srEy+nvbYxHWE3CbZOHxT9JPEFl8vGZ5BMe9SXf49KlwZqN/WPm5Tn/lUjTXZRKJxhGSgd6rbIgTIPLAME/sJEF+aO72vWbzXSzyeGX4hVziVVOldVCIJZtwxR+pAtBnzjJfnGWxCI4Zun204HP+911KcWw+i4yvv76INmTne3mXWe4Oio1YhJSsfxfwF+MCx813230kbs398+HQ+0tRU6xzfNvMJVNaUxvF23EC/R4uYgi074kBq1KYuL3Xdxnb9acBKIQHkO0wmeNGDY73SoPCGcwpQDXtMn7gqpbijUs92WEHDcsDOI1FdYRiEER33pAeKbkrVBRpVwVJXWcZWp9Yuw8vYFOEL6CsCttru0ukPWmrWPKjvw2gk+25Qae4OirNZi4hz2BdVIqfXM+cy+LaSF/zaCbgME/KYm1ZFdIAgyxJvEOmREBbe2r2egA7VjsmHK8esteE2dz+HJ0IIDAL9RnuIN/tbqqSZYmpLuvc7SnLeqHGn4Ka3yCdqqQASnA9eQkuw1NPgFXiU=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
