travis:
  secure:
    BINSTAR_TOKEN: S5IwZknt3zsSKzhyHmZyQlSVPtMCUrkC+mwb3ebsh7SBlBnb5EKUL5M/VTIH5sngQj1llR184RsDen8Xqoj8fT101k9AtkESZAEqy8NTIIMGYjhDMAB2pbNlwf0azkl/Hp4DJjvBY6GpC0SHFygkOsGm7vbPWzlQzEGp64ny8SC/T85gaGI6NaWoobtJTHUq8Cx+LD9OmHnoY3fteH7SO5XvxXYW31h2ie/tQ+sbgjrQSU7+2Jg0M2EMA9J0B53+FBlLcvmWxAjdpCklbHxuWMAJ0GAi7upabrlLejS4a6Fk1v03hgaFNdV/lec6HH54g7rYZBmlViEA2RSQnZ5DzSlb916hSqSyf3YKuujUPOLXIDBw8Hn22bdqaQQhsL5jwUov0Dh8bXsD+HMHM5rvLua1/4sq7lDsT7fylmCVTHOa9ShKXxqBN26DHjIdxEUTjDvOFZqz9dIt/VJOvUMC+x2Mx3D2WndB6LOF6D/ikMmrtx+11xIMtS2ts0EUtTy7/BjgtvIxfSK5b4JFxxKA2xD1qzETafcwxt+5vXRWLpTdtbXXca5t+EFv1QoHyGe9EENzzJN3c9rFYuVZMTFVSbSO5UFxJVK9+pLlGfUYxSl8PF6tFmt0RWt7v8U3b6yS8QJoNHTtUStf+o079ZEHgXLAKgK9pLic7dahnw1CJ8g=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
