travis:
  secure:
    BINSTAR_TOKEN: DqepPJQ6GNlsSwQ7Ycz1+dZ96mvAy13CDHvYV8PYtjvz6D4GCnHxGRR7y/5YN7McEaQA0VwPrniPjJalbQdzPGxtz34vYOemjz+yTMAPSWQ/+YINvvsLzXdLmhErFkrFsq8qpbuCzckmV5ONXAH6RoX3s776DiWhvsa3eIFvhkpA9QmQfDqnUaP4uT4cjjUfxOCY7PgsRmU0/5Ql4jMFLL8nE2yilCeGypUsW4p829vVJVGNgk+SYNzCWeTB0xIdKjhvSAvXr09Y74MORu4S6TSTVCEWGSe24je0VV37BxhhHuSuhjzEVkaTzM3JsmzO9B/IuO6P2dkb5Y8bXrNyU8/SZ+LfDLj5zldr4vvNI13BjuAIZmG1Lt9k6HaewBBlUAve1Pn7jfA9lsa6aWqkAj8VjaPIvMdhrB7CqMZWXjDbSL8bskvNGstz8vzBLRbdCSygAZVMVWR/7iPTD9Ni5pw+p15cpG3VTu4m9/D3VgAhMU0g+oiMI9K8T5iewTOhbZj7m0CCXydU/Jl5wIw2qtBUFyuBO04t/NlggodeKckLqN1hOjVhC9dKsggOGz8xZ/2Cdopkqr2ozj2zRCgZn9IT5jTfaBpyy5SOPUJ38ECWKNB7tP5lu4YpHiRpeyK1h75liBcm/O3sV1W05GmRRPB9gGx8xSrz6oTGmdpdqYk=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
