travis:
  secure:
    BINSTAR_TOKEN: lnsKc+eV3AUwzN0bG495ONPXbV9QoKxewLiorW1R7qc7/rSWHtAH5mMO5xHbbfvZT6ZVt7zQgnPRlr/i8b91mdhuO8hopJ/xDaGmbtsY6QmG4/JDLU8GcoKy+zln5D2esl9R8Rw2avOkOFfM9MtwI7o3hY8rNkm3Yfgzm4zu20Mo1r579sZR6naSlIWgw/ll1y7FpBIcicjf9Hd60Og9DhpSsoSdKWn3mHLOtqUuV/zzmOLcwaTZTXEQjINZeL/UHZaB3E3XSRHw/FudBSxK+/oIvKDFJ9KxqH2Du7JkOUgEUnB4bVwCUQ3HMD9pGmeBxg4lDoKtQ1I+g68fjcS0HRBmwK8bUHZYFeHuvkicRwfh82rpOnqQKBxZ7E3uMmD+WDP2tpD0R7PxaYbo7pgPMjxTRt3oZAEPThXDBS3WQaE/y0E805+/zriK5hHv1xbZagYRtR0hI8xoluFeZ/HtzMdmkf3Es4ap/P+/h1LYDKaHBh1HgGH95y05I/QGcx8cTwI09wwe2EdS6w4jex4wJu1IdHEdYn4pniX0+/FWTW4qReB9mKTgKpEmPJ2x1/rv4FMBIcu1i+jZdimbVlSeC2XZ2dxvAY7vp37ScCjkt6+SrxS7sDTA3Ay4r+t8w1Rs5FMFBGixKpxePT30rUW/Ji1hznLmaw/tX/++ZyNzMPM=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
