travis:
  secure:
    BINSTAR_TOKEN: quzk3znnOO+fgjMBPzukc/D42yyLvsAR0+4kGh5s2qtwnmLiuKVxqsfuW/Wvh72P2jQzAPIbqwdgURFEeHddjxfw0+VwxwF35tvzDu6B6Oy9m+bWrEwF8wYBgjUDw4AQZ/c66Y5bqXExv/1vWtMpy7LqvlMK9WOUQ9qHF6k0o8kEd9SSN/nJFCLpjIIQKUMlr3iQkFhh4D7qHjh7VnfDB0iBi7zH42FPB3jdHrb0J2ImNU9x1QEQwoRrfOkpYNl3YrpiTgcvubw0YyEfV4yqsHWVmjYkG7OVfNreR6DzN0tWhUS9/IV+lLG2hiaGkdrEeYWhE4iN4hCbt1AZVXkihki1aLzbk9YRcuK4XlGsBX1AtkJ33fqBdy7o9UrjsgcMT0HiQc2CE5978YOYyhpncOjDucxLATvDnJm01xEzzedVGew7G1T3SWbT8eqWtm6D469UrkNQxgJTzdorGrEAqpD8mVPbML4/cAnNsPBFduWsPItsiBTVfbbh+0anvLbicPnXnVbVa52jQBe/a5pHLVLCc8tyxFm8osrYt2+Mogd8jbhrwIMYCROqgI42sY9N/VvimE8sA5tp2LBrcadGMmZqyzLNbZpTyCI9wvtkASMJSsuSWndfJX0kFTpw5V21BhrDUmgw/elS6VLe6Lxa1JT748SxfNh2rYF2X/cY55w=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
