travis:
  secure:
    BINSTAR_TOKEN: oT3Z8EZLGXXlV7A+YFVaMONR5Ec97/ef7KtHgkNVWQPlGaQ/UndEHzcqrIn8FX2lsB6OH7DLvt59+dP3TRRQJSReo2H+7CnA6zwUUBJm31oux2bULTNX/h3tHNy2IEMH6NKgVM5suhMtQs4agWdPnRf7e6y/QC+tUSD/4WsKA4sf4MNb3+Z0sE4I+WCXtTuD0XHkk4/Ndh4KCQRrPHSGjQz3vvBu5EwelxZP83gzL6fiy5oTmUYgERhiMn6nSox3N+sfAE+M5OxhUAZRmTiZ/8tYRBTJoGOudknBh0uHygXKs4Y/T63kKeTXZd+xnM774S9DuZ1SnphdJIAGqaXwCd4VY9tm/11UU9MrRgHL0Zn+hxLsulCRTIRP4wfQeEXwl0LXdBp/8I0LwKkjQOhTIJw3NCyqd1BhM9slIaEYjQ6zDf6h0a7Sq5I1oTljE7YR/z1VzbSnkM04xWwzd3HoIpzp7UDeH4LNbtaeFE8L/Xu1kL7+nD/7UoBK3Pj6lcWUBU1+Wz0t0niHtNhQgUr2FwZK+S0ez5ca6pElfcti+fl36ecormC0YTdRNXIhesOx9DJ+DmmHMxWjsnjpKKNGtWlmbEe4qZ2eoViTUoTmmre/fug1gmpfetcjYQHDc1xUjb7xNXXESOjX82RB6BlRELT1q+m0eHHybg3MzWypGWs=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
